(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},f=ca(this),l=function(a,b){if(b)a:{var c=f;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}},da="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ea={a:!0},p={};try{p.__proto__=ea;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m,fa=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};l("globalThis",function(a){return a||f});
l("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});var r=this||self,t=function(a){return a};var ha=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var u={},v=null;var ia="function"===typeof Uint8Array;var w="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function x(a){Object.isFrozen(a)||(w?a[w]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function y(a){return null!==a&&"object"===typeof a&&a.constructor===Object}var B;function ja(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(ia&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!v){v={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));u[e]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===v[k]&&(v[k]=h)}}}b=u[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var z=a[g],A=a[g+1];
k=a[g+2];h=b[z>>2];z=b[(z&3)<<4|A>>4];A=b[(A&15)<<2|k>>6];k=b[k&63];c[e++]=h+z+A+k}h=0;k=d;switch(a.length-g){case 2:h=a[g+1],k=b[(h&15)<<2]||d;case 1:a=a[g],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}return c.join("")}}return a};function ka(a,b){if(null!=a)return Array.isArray(a)||y(a)?C(a,b):b(a)}function C(a,b){if(Array.isArray(a)){for(var c=Array(a.length),d=0;d<a.length;d++)c[d]=ka(a[d],b);if(b=Array.isArray(a)){var e;w?e=a[w]:e=a.g;b=(null==e?0:e)&1}b&&x(c);return c}e={};for(c in a)e[c]=ka(a[c],b);return e}function la(a){a=ja(a);return Array.isArray(a)?C(a,la):a};var ma;var D=function(a,b,c){var d=ma;ma=null;a||(a=d);d=this.constructor.B;a||(a=d?[d]:[]);this.h=(d?0:-1)-(this.constructor.A||0);this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],y(d))){this.j=a-this.h;this.i=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.h),this.i=null):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.j?(a+=this.h,(d=this.g[a])?Array.isArray(d)&&x(d):this.g[a]=na):(oa(this),(d=this.i[a])?Array.isArray(d)&&x(d):this.i[a]=na)},na=Object.freeze(x([])),oa=function(a){var b=
a.j+a.h;a.g[b]||(a.i=a.g[b]={})},E=function(a,b,c){var d;(void 0===d?0:d)||b>=a.j?(oa(a),a.i[b]=c):a.g[b+a.h]=c;return a};D.prototype.toJSON=function(){var a=this.g;return B?a:C(a,la)};function pa(a,b){return ja(b)}D.prototype.toString=function(){return this.g.toString()};var F=function(a){D.call(this,a,-1,qa)};F.prototype=da(D.prototype);F.prototype.constructor=F;if(q)q(F,D);else for(var G in D)if("prototype"!=G)if(Object.defineProperties){var ra=Object.getOwnPropertyDescriptor(D,G);ra&&Object.defineProperty(F,G,ra)}else F[G]=D[G];var qa=[6];var H,sa=function(){if(void 0===H){var a=null,b=r.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:t,createScript:t,createScriptURL:t})}catch(c){r.console&&r.console.error(c.message)}H=a}else H=a}return H};var I=function(a,b){this.g=b===ta?a:""};I.prototype.toString=function(){return this.g+""};var ta={};var ua={},J=function(a,b,c){this.g=c===ua?a:""};J.prototype.toString=function(){return this.g.toString()};/*

 SPDX-License-Identifier: Apache-2.0
*/
function va(a){return a instanceof J&&a.constructor===J?a.g:"type_error:SafeHtml"};function wa(a){var b=a.write,c=b.apply,d=fa.apply(1,arguments).map(va);if(!(d instanceof Array)){var e="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];d=e?e.call(d):{next:aa(d)};for(var g=[];!(e=d.next()).done;)g.push(e.value);d=g}c.call(b,a,d)};var za=function(a,b){if(!xa()){var c=Math.random();if(c<b)return c=ya(),a[Math.floor(c*a.length)]}return null},ya=function(){if(!globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},xa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return ha(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Aa)||1E-4>Math.random()}),Aa=function(a){var b;
a:{if(b=r.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};var Ba="platform platformVersion architecture model uaFullVersion bitness".split(" "),Ca=function(){return r.navigator&&r.navigator.userAgentData&&"function"===typeof r.navigator.userAgentData.getHighEntropyValues?r.navigator.userAgentData.getHighEntropyValues(Ba).then(function(a){var b=new F;b=E(b,1,a.platform);b=E(b,2,a.platformVersion);b=E(b,3,a.architecture);b=E(b,4,a.model);b=E(b,5,a.uaFullVersion);return E(b,9,a.bitness)}):null};var Da=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(d){}return!0}(r,!1)?"https:":"http:",Ea={},Fa=(Ea[1]="A4/Htern2udN9w3yJK9QgWQxQFruxOXsXL7cW60DyCl0EZFGCSme/J33Q/WzF7bBkVvhEWDlcBiUyZaim5CpFQwAAACceyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQ29udmVyc2lvbk1lYXN1cmVtZW50IiwiZXhwaXJ5IjoxNjQzMTU1MTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlLCJ1c2FnZSI6InN1YnNldCJ9",
Ea);var Ga={v:1,o:4,s:5,u:12},K={m:"40004006",l:"40004007"};function Ha(){return{1:.5,4:.02,5:.001,12:.001}}function Ia(){var a=Ja,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in Ga)if(b=a[Ga[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Ka(){var a=r.dcmads;if(null!=a.eids)return a.eids;var b=r.navigator;return b.connection&&b.connection.saveData?(a=za([K.m,K.l],a.expts[4]))?"4|"+a:"":""}function La(){if(!r.dcmads.uach){var a=Ca();a&&a.then(function(b){var c=r.dcmads;a:{B=!0;try{var d=JSON.stringify(b.toJSON(),pa);break a}finally{B=!1}d=void 0}c.uach=d})}};try{r.dcmads=r.dcmads||{};r.dcmads.startTime=(new Date).getTime();var Ma=r.dcmads,L=r.dcmads.version,M={loader:236};if(L)if(M.experiment=L.experiment,81==L.number||"p"==L.number)M.number=81;else if(81==L.number||"c"==L.number)M.number=81;if(!M.number){var Na=za([81,81],0);M.experiment=!!Na;M.number=Na||81}Ma.version=M;var Oa=r.dcmads,Pa,Ja=r.dcmads.expts,N;N=void 0===N?Ha:N;Pa=Ia()?Ja:N();Oa.expts=Pa;r.dcmads.eids=Ka();r.dcmads.ots=Fa;La();var Qa="4|"+K.l,O,Ra=r.dcmads.version,Sa=Ra.number,Ta="";
Ra.experiment&&81==Sa&&(Ta="?rxp=81x81");var Ua="impl_v"+Sa+".js"+Ta,Va=r.document,Wa=Va.currentScript||Array.from(Va.getElementsByTagName("script")).pop();O=(0==(Wa&&Wa.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+Ua;if(r.dcmads.eids===Qa){var Xa=r.document,P,Ya=sa(),Za=Ya?Ya.createScriptURL(O):O;P=new I(Za,ta);var Q,R=Xa;R=void 0===R?document:R;Q=R.createElement("script");Q.src=P instanceof I&&P.constructor===I?P.g:"type_error:TrustedResourceUrl";var $a,S,ab=(Q.ownerDocument&&
Q.ownerDocument.defaultView||window).document,T=null===(S=ab.querySelector)||void 0===S?void 0:S.call(ab,"script[nonce]");($a=T?T.nonce||T.getAttribute("nonce")||"":"")&&Q.setAttribute("nonce",$a);var U=Xa.getElementsByTagName("script")[0];U&&U.parentNode&&U.parentNode.insertBefore(Q,U)}else{var bb=r.document,cb='<script src="'+O+'">\x3c/script>',db=sa(),eb=db?db.createHTML(cb):cb;wa(bb,new J(eb,null,ua))}}catch(a){if(.01>Math.random()){var V="";try{var W,X=a.toString();a.name&&-1==X.indexOf(a.name)&&
(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&(X+=": "+a.message);if(a.stack){var Y=a.stack,Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var fb;Y!=fb;)fb=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var gb=r.dcmads.eids,hb=document.createElement("img");hb.src=Da+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=236&context=554"+((gb?"&eids="+gb:"")+"&msg="+
V);(r.google_image_requests=r.google_image_requests||[]).push(hb)}};}).call(this);
